### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/statistics#12]
It would be cool to have some features of this MOD:
https://www.phpbb.com/customise/db/mod/phpbb_statistics/

Like Forum Activity, Forum Contributions. So we will know which users send more topics, which topic have more views, more subscribes, more favorites, etc.
And maybe support addons for which topics has more likes for example.

Best regards

**Comment by Leinad4Mind** [comment]
In fact I've found this extension right now: https://github.com/oxpus/Basic-Statistics/tree/master/oxpus/basicstats

And thats what I was asking. So if you dont feel to add it on yours, its ok. I would use that one. If you want to check that extension to pick ideas, fell free. :)

Best Regards

**Comment by ForumHulp** [comment]
Hello Daniel
I tried to look at the mod but the pictures aren't working anymore. Something like https://github.com/ForumHulp/postsstats

**Comment by Leinad4Mind** [comment]
I'll take a look. 

But here you've some pictures: http://imgur.com/a/Xx5J7
