### ISSUE TITLE
php warning fsockopen

### ISSUE THREAD

**Issue by Leinad4Mind** [ForumHulp/statistics#13]
I'm getting this error now:

> [phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/statistics/event/listener.php on line 165: fsockopen(): unable to connect to www.ip-api.com:80 (Connection timed out)

**Comment by ForumHulp** [comment]
Look at your server settings, f_open I think

 

Greetz

 

 

Van: Daniel Mota [mailto:notifications@github.com] 
Verzonden: donderdag 29 december 2016 19:57
Aan: ForumHulp/statistics <statistics@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [ForumHulp/statistics] php warning fsockopen (#13)

 

I'm getting this error now:

[phpBB Debug] PHP Warning: in file [ROOT]/ext/forumhulp/statistics/event/listener.php on line 165: fsockopen(): unable to connect to www.ip-api.com:80 <http://www.ip-api.com:80>  (Connection timed out)

**Comment by Leinad4Mind** [comment]
Thks for the tip. I'll check that.
